# Generated by Django 3.2.6 on 2021-08-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_type_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('type_of', models.CharField(choices=[('BG', 'Beginner'), ('IN', 'Intermediate'), ('PR', 'Pro'), ('EX', 'Expert')], max_length=2)),
            ],
        ),
    ]
