# Generated by Django 3.2.6 on 2021-08-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
