# Generated by Django 3.2.6 on 2021-08-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_pdf', models.FileField(upload_to='resume')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
